### ISSUE TITLE
Slimebot DMs not accepting new Wordle games despite old games being finished

### ISSUE THREAD

**Issue by thechairguy** [perpetualcacophony/slimebot#13]
After playing a daily Wordle game in DMs, it is not possible to play Wordle in DMs again without requesting a daily game indirectly through the private server. `..wordle random` and `..wordle daily` (when a daily is available) will only prompt the response `there's already a game being played in this channel!`, as well as a link to the most recently completed daily Wordle game. 
![image](https://github.com/perpetualcacophony/slimebot/assets/85413458/1ca421ea-aeb5-4f73-ad40-576ec9252df8)
![image](https://github.com/perpetualcacophony/slimebot/assets/85413458/a09a3f58-709f-48c4-b52a-5f7f9963d922)
The bot does not fully register that the game has been completed, and treats the DM as though the game is still running, despite the game being completed and no longer taking new words.
![image](https://github.com/perpetualcacophony/slimebot/assets/85413458/d247d7c5-2ed2-4ecc-b90e-3835c31775b7)

**Comment by perpetualcacophony** [comment]
initial guess: probably isn't removing the lock when played in a DM
gonna try to replicate

**Comment by perpetualcacophony** [comment]
cannot replicate, how did you end the daily game?

**Comment by thechairguy** [comment]
i ended the daily game as normal, by entering the correct word. i suspect that the issue arises in requesting the daily game from the private server?
